### ISSUE TITLE
tests that test the -P option fail on perl 5.10.1

### ISSUE THREAD

**Issue by doy** [bingos/devel-patchperl#13]
Trying to install 5.10.1 via perlbrew, and I get this build output: http://paste.tozt.net/2013-05-18Lyg6T4J_-build.perl-5.10.1.log

I'm on Arch Linux, and `cpp --version` gives `cpp (GCC) 4.8.0 20130502 (prerelease)`. This is likely also an issue on earlier versions of perl, although I haven't tested them. It's not an issue on any later versions, because the `-P` option was removed in 5.12.

**Comment by bingos** [comment]
Oki doki.
