### ISSUE TITLE
Get PatchPerl version used to build perl, at runtime

### ISSUE THREAD

**Issue by exodist** [bingos/devel-patchperl#21]
It would be very handy to be able to tell what version (if any) of patchperl was used to build the currently running perl. Note: This is probably different from any version installed.

As of a recent patch `perl -V` shows this info, and on recent perls this can be obtained using the `Config::local_patches()` function. However on older perls this function is not present. For instance in perl 5.10.0 there is no way I have found to detect the patchperl used to build the perl from within perl code, except to shell out to `$^X -V` and parse the output, which is awful, and probably not very portable.

Patchperl could patch Config.pm to expose the `$Config{BuiltWithPatchPerl} = VERSION`. Then in perls patched with the newest version it becomes trivial to check this.

**Comment by Tux** [comment]
@exodist did you know about Config::Perl::V ?
Does that add enough information?

**Comment by exodist** [comment]
@Tux Config::Perl::V is not core, as such it can't help me to detect the patchperl version in core modules such as Test::Builder/Test::Stream.

**Comment by Tux** [comment]
@exodist Config::Perl::V is core since 5.17.9, but I see your point

**Comment by exodist** [comment]
http://perldoc.perl.org/index-modules-C.html

I don't see it on this list for 5.22, is it simply unlisted?

**Comment by bingos** [comment]
I've commited 6571d84e655c6feddb346beb46d44a87d41c1ef7 which adds 'BuiltWithPatchPerl' the only way I could fine to do it via patching Configure.

If this is acceptable I shall tag a release.

**Comment by exodist** [comment]
I am afraid I don't know much abotu the perl build system, but if this adds ```$Config{BuiltWithPatchPerl}```  then I am a big +1 on it.

**Comment by bingos** [comment]
Yes, that is exactly what it does :) I've tested it with blead and back as far as v5.6.0

**Comment by exodist** [comment]
Awesome! :-)

**Comment by bingos** [comment]
This looks like it was resolved years ago.
