### ISSUE TITLE
Update hints for Cygwin

### ISSUE THREAD

**Issue by yak1ex** [bingos/devel-patchperl#28]
Now, Cygwin requires -D _GNU_SOURCE in ccflags 
After Perl-5.24.3 and Perl-5.26.1 (inclusive), it is reflected in hints/cygwin.sh.
See https://perl5.git.perl.org/perl.git/commitdiff/fd998cbffc88a8e50fa34259c36a8db338168383

**Comment by bingos** [comment]
Going to go out on a limb and assume this is resolved as I have updated all the hints since this ticket was raised.

Many thanks.
