### ISSUE TITLE
patch_source fails with 5.8.1..8

### ISSUE THREAD

**Issue by andk** [bingos/devel-patchperl#30]
On git checkouts for perl-5.8.1 up to 5.8.8 this fails for me with both PatchPerl 1.58 and 1.60. Tested with debian stretch and ubuntu cosmic.
```
Devel::PatchPerl->patch_source("5.8.1", ".")  # up to 5.8.8 
```
perl-5.8.9 is ok with 1.60 and not ok with 1.58.
Devel-PatchPerl-1.56 seems ok for all of them (have only tested a few)

Some fail on patching Configure, some on patching h2ph.PL. Have not paid enough attention yet to the differences.

**Comment by bingos** [comment]
This was fixed in version 1.62

Many thanks.
