### ISSUE TITLE
Leftover file `meh` in tarball?

### ISSUE THREAD

**Issue by perlpunk** [bingos/devel-patchperl#37]
The tarball contains a file called `meh`: https://metacpan.org/source/BINGOS/Devel-PatchPerl-1.76

Is this supposed to be there or just a leftover that should be removed?

We stumbled upon this while maintaining the perl modules repository in openSUSE.

**Comment by bingos** [comment]
*sigh*

I shall upload a fixed tarball.

Thanks for being more observant than me. :+1:

**Comment by perlpunk** [comment]
thanks!
