### ISSUE TITLE
Time::Local tests still failing in perl-5.16.3 in perlbrew

### ISSUE THREAD

**Issue by Scimon** [bingos/devel-patchperl#41]
I did a perlbrew install of 5.16 (for work reasons). Previously we removed the Time-Local test from the tarball and then manually installed Time::Local after the build. Unfortunately this breaks with the updated patchperl.

The patched test is now failing with this message : 

```
simon@simon-ThinkPad-X1-Carbon-5th ~/perl5/perlbrew/build/perl-5.16.3/perl-5.16.3/cpan/Time-Local $ prove -l t
t/Local.t .. 1/? Second '59.1' out of range 0..59 at t/Local.t line 98.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 108.
t/Local.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
All 108 subtests passed 

Test Summary Report
-------------------
t/Local.t (Wstat: 65280 Tests: 108 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=1, Tests=108,  0 wallclock secs ( 0.06 usr  0.01 sys +  0.15 cusr  0.01 csys =  0.23 CPU)
Result: FAIL
```
I'm going to investigate and see if I can work out a fix.

**Comment by Scimon** [comment]
It looks like the test has been updated from a later version of Time::Local that accepts fractional seconds but the library hasn't. 
Can we comment out lines 30 and 31 in the test? Or move the fractional seconds into the bad time section?

**Comment by bingos** [comment]
After I released the new version last night I found a better solution than blindly backporting the more recent test file. Hope to get a new version out today at some point.

**Comment by Scimon** [comment]
Thanks, that's great to hear.

**Comment by Scimon** [comment]
I'm running a build now. I'll update the ticket when it's done :)

**Comment by Scimon** [comment]
The Time::Local test passed fine. Thanks for the fix!
