### ISSUE TITLE
Failed to apply Devel::PatchPerl 1.98 on Perl v5.22.4

### ISSUE THREAD

**Issue by mackdoughe** [bingos/devel-patchperl#44]
This issue is an extension of #42 for Perl v5.22.4 specifically. I used perlbrew to try to install perl-5.22.4 with patchperl v1.98 and got the following error:
```
Auto-guessed '5.22.4'
patching Configure
patching cpan/Time-Local/t/Local.t
patching pp.c
patching Configure
1 out of 6 hunks FAILED -- saving rejects to file Configure.rej
Died at /home/testuser/perl5/perlbrew/bin/patchperl line 1780.
```
Looking at Configure.rej you can see:
```
--- Configure
+++ Configure
@@ -22961,7 +22961,7 @@ fi

 : add -D_FORTIFY_SOURCE if feasible and not already there
 case "$gccversion" in
-4.*)   case "$optimize$ccflags" in
+[456789].*|[1-9][0-9]*)        case "$optimize$ccflags" in
        *-O*)   case "$ccflags$cppsymbols" in
                *_FORTIFY_SOURCE=*) # Don't add it again.
                        echo "You seem to have -D_FORTIFY_SOURCE already, not adding it." >&4
```

The problem seems to be that it's trying to add that last section to line 22961 but for v5.22.4 it should be at line 23009. I looked at some of the other line numbers for other version numbers and they equally seem to be off so I think this new patch for GCC10 might cause some patching problems due to the line numbers.

**Comment by zakame** [comment]
Can confirm this as well while preparing updates for https://github.com/Perl/docker-perl

**Comment by zakame** [comment]
cf https://github.com/Perl/docker-perl/runs/737449815

It also affects patching for 5.24 as well.

**Comment by bingos** [comment]
patch can fuzz around line number differences. What has happened with the v5.22 and v5.24 maintenance releases is that changes to Configure has been backported.

I have adjusted ( and tested ) the patch application for v5.22 and v5.24 and it should all work fine now.

Version 2.00 will be shortly on CPAN

Many thanks.

**Comment by mackdoughe** [comment]
Thanks, that fixed it!
